version: '2'
services:
  db:
    build: ./db/
    image: wuattiroro/devops_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=geo
      - POSTGRES_USER=Roman
      - POSTGRES_PASSWORD=
  server:
    build: ./RGeo/
    image: wuattiroro/devops_server
    ports:
      - "80:80"
    links:
      - db
